package com.nts_ed.ks.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import com.nts_ed.ks.dto.Employee;
import com.nts_ed.ks.param.LoginParam;
import com.nts_ed.ks.repository.EmployeeRepository;

@Controller
@RequestMapping(path = "/")
public class IndexController {
	@Autowired // This means to get the bean called TEmployeeRepository
				// Which is auto-generated by Spring,we will use it to handle the data
	private EmployeeRepository employeeRepository;
	
	@PostMapping(path = "testform")
	public String testform(LoginParam param,@Validated LoginForm loginForm,BindingResult result, Model model) {
		if(result.hasErrors()) {
			return "index";
		}
		
		List<Employee> isExists1 = employeeRepository.checkEmployeeID(param.getId());
			if (isExists1.size() == 1) {
			List<Employee> isExists = employeeRepository.checkEmployee(param.getId(), param.getPass());
			if (isExists.size() == 1) {
				return "main";
			} else { 
				model.addAttribute("msg1","パスワードが間違っています。");
				return "index";
			} 
		} else {
			model.addAttribute("msg2","社員IDが存在しません。");
            return "index";
			}

	}	

	@GetMapping(path = "/")
	public String index(LoginForm loginForm) {
		// This returns a JSON or XML with the users
		// 項目の初期化が書く必要になります
		return "index";
	}
}
