package com.nts_ed.ks.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import com.nts_ed.ks.dto.Employee;
import com.nts_ed.ks.param.LoginParam;
import com.nts_ed.ks.repository.EmployeeRepository;

@Controller
@RequestMapping(path = "/")
public class IndexController {
	@Autowired // This means to get the bean called TEmployeeRepository
				// Which is auto-generated by Spring,we will use it to handle the data
	private EmployeeRepository employeeRepository;
	
	@PostMapping(path = "/login")
	public @ResponseBody List<Employee> login(@RequestBody @Validated LoginParam param) {
		//　社員のチェックを行います
		// This returns a JSON or XML with the users
		List<Employee> isExists = employeeRepository.checkEmployee(param.getId(), param.getPass());
		if (isExists.size() == 1) {
			return null;
		}
//		return "";
		return null;
	}

	
	@PostMapping(path = "testform")
//	public @ResponseBody String test(@ModelAttribute LoginParam param) {
//		// 社員のチェックを行います
//		return null;
//	}
	
	public String testform(@ModelAttribute LoginParam param) {
		List<Employee> isExists = employeeRepository.checkEmployee(param.getId(), param.getPass());
		List<Employee> isExists1 = employeeRepository.checkEmployeeID(param.getId());
		if (isExists1.size() == 1) {
			
			if (isExists.size() == 1) {
				return "main.html";
			}
			else {
				return "passerror.html";
			}
		}
		else {
			return "iderror.html";
		}
		
	}

	
	@GetMapping(path = "/")
	public String index() {
		// This returns a JSON or XML with the users
		// 項目の初期化が書く必要になります
		return "index";
	}
}
